### ISSUE TITLE
In filesystem example what if api comes up first?

### ISSUE THREAD

**Issue by scytacki** [donaghhorgan/compose-sync-examples#1]
In the filesystem example:

If the api container comes up first and touches `/var/rproxy/up`, then the rproxy container comes up won't it miss this change on the filesystem and then never start?

https://github.com/donaghhorgan/compose-sync-examples/blob/c84f70b94fd8a152fa8cb4fdb66be7ecb2dbcf10/file-system/docker-compose.yml#L8

I was thinking that you could have the rproxy wrapper script check for the existence of `up`, but because it is on a named volume, `up` will be there the second time even before the api container comes up.

**Comment by donaghhorgan** [comment]
That's a fair point, but it would only happen in situations where `rproxy` takes longer to start than the total amount of time taken for `db` and `api` to start (given that `api` is itself waiting on `db`). In most cases the database and API application would take considerably longer to start than a lightweight Nginx configuration - but it depends on your application, I suppose :D
